version: '3.8'

services:
  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: raganything-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Backend API
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: raganything-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/app:/app/app
      - ./raganything:/app/raganything
      - ./rag_storage:/app/rag_storage
      - ./output:/app/output
      - ./inputs:/app/inputs
    depends_on:
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # Frontend (Development Mode)
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dev.Dockerfile
    container_name: raganything-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  redis_data:
